### ISSUE TITLE
app-template: link to laxarjs.org/docs rather than GitHub

### ISSUE THREAD

**Issue by x1B** [LaxarJS/generator-laxarjs#21]
When linking to docs from the generated application, we should link to the latest http://laxarjs.org/docs/ for the corresponding LaxarJS major version, and not to the manuals / README on GitHub.

**Comment by jonaswjs** [comment]
Implemented on `master` (`v1.6.0`)

**Comment by jonaswjs** [comment]
Created https://github.com/LaxarJS/generator-laxarjs2/issues/1 for version 2.x
