### ISSUE TITLE
templates: adjust to LaxarJS v2 changes

### ISSUE THREAD

**Issue by x1B** [LaxarJS/generator-laxarjs#22]
Several changes (some breaking, some stylistic) are introduced with LaxarJS v2 and should be reflected by the Yeoman generator as well (also bumping the major to v2.0).

Some issues are especially relevant:
- webpack as default bundler
- removing compatiblity magic [#273](https://github.com/LaxarJS/laxar/issues/273)

**Comment by alex3683** [comment]
Use static css bundle for production mode.

**Comment by x1B** [comment]
_Closing:_ work on this has moved to [LaxarJS/generator-laxarjs2](https://github.com/LaxarJS/generator-laxarjs2/)
