### ISSUE TITLE
templates: upgrade to latest v1.x

### ISSUE THREAD

**Issue by x1B** [LaxarJS/generator-laxarjs#23]
The templates should reference LaxarJS v1.3

**Comment by x1B** [comment]
Also, `laxar-mocks` v1.1 and possibly a couple of other deps.

**Comment by x1B** [comment]
@jonaswjs FYI

**Comment by jonaswjs** [comment]
Fixed on `master` (`v1.6.0-pre`) and on `release-1.5.x` ( `v1.5.2`).
